### ISSUE TITLE
babel-core browser

### ISSUE THREAD

**Issue by khankuan** [babel/babel.github.io#637] opened 2015-12-14 02:19 UTC
Hi, I'm using 6.3.17 and using babel on the browser:

```
import babel from 'babel-core';
```

And got this error: 
```
ERROR in ./~/babel-core/lib/api/node.js
Module not found: Error: Cannot resolve module 'fs'
```

The docs mentioned that `babel-core/browser` is deprecated and to use `babel-core`. Do I need any special configs to enable babel for browser?

**Comment by prathamesh-sonpatki** [comment] 2015-12-14 02:20
Duplicate of https://github.com/babel/babel.github.io/issues/559

**Comment by khankuan** [comment] 2015-12-14 02:25
I tried using `babel-browser` but it didnt work as well :/

**Comment by thejameskyle** [comment] 2015-12-14 22:29
`babel-browser` is deprecated and removed, it was never meant to be used as a normal build tool. You'll need to switch to an actual build system.

Also, this is not the appropriate place for support requests. http://slack.babeljs.io/ or http://discuss.babeljs.io/ is the place to take this.

**Closed by thejameskyle** 2015-12-14 22:29 UTC
