### ISSUE TITLE
Link shortener REPL

### ISSUE THREAD

**Issue by benjamingr** [babel/babel.github.io#162] opened 2015-02-27 17:31 UTC
Several times already I've tried sharing REPL code - it currently works with GET parameters but it's huge. This makes me go to goo.gl in order to save the code. 

http://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=function%20get(prop)%7B%0A%20%20if(typeof%20this%20%3D%3D%3D%20%22object%22%20%26%26%20this%20!%3D%3D%20null)%7B%0A%20%20%20%20return%20this%5Bprop%5D%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20undefined%3B%0A%20%20%7D%0A%7D%0Alet%20a%20%3D%20%7B%22foo%22%3A%20%7B%22bar%22%20%3A%205%7D%7D%3B%0Aconsole.log(%22a.foo.bar%22%2C%20a%3A%3Aget(%22foo%22)%3A%3Aget(%22bar%22))%3B%0Aconsole.log(%22a.foo.baz%22%2C%20a%3A%3Aget(%22foo%22)%3A%3Aget(%22baz%22))%3B%0Aconsole.log(%22a.asda.bar%22%2C%20a%3A%3Aget(%22asda%22)%3A%3Aget(%22bar%22))%3B%0A

vs 

http://goo.gl/iHfgW9

A link shortener would be immensely useful.

**Comment by thejameskyle** [comment] 2015-02-27 19:31
Duplicate of #66 and babel/babel#423

**Closed by thejameskyle** 2015-02-27 19:31 UTC
