### ISSUE TITLE
https://babeljs.io/docs/plugins/preset-stage-2 is 404

### ISSUE THREAD

**Issue by jameswomack** [babel/babel.github.io#501] opened 2015-10-30 21:00 UTC
Going to https://babeljs.io/docs/plugins/preset-stage-2 results in a 404. Same for https://babeljs.io/docs/plugins/preset-stage-1 etc.

**Comment by hzoo** [comment] 2015-10-30 21:01
Yeah making a fix now - duplicate of https://github.com/babel/babel.github.io/issues/500 too.

**Closed** 2015-10-30 21:08 UTC
